# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# xy2fc.py
# Created on: 2015-09-09 13:09:29.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: xy2fc <Input_Table> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Input_Table = arcpy.GetParameterAsText(0)
if Input_Table == '#' or not Input_Table:
    Input_Table = "C:\\GisData\\CMPDData.gdb\\Adult_Arrest" # provide a default value if unspecified

# Local variables:
Adult_Arrest_Layer = "Adult_Arrest_Layer"
Adult_Arrest = "C:\\GisData\\CMPDData_FC.gdb\\Adult_Arrest"

# Process: Make XY Event Layer
arcpy.MakeXYEventLayer_management(Input_Table, "x_coord", "y_coord", Adult_Arrest_Layer, "PROJCS['NAD_1983_StatePlane_North_Carolina_FIPS_3200_Feet',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Lambert_Conformal_Conic'],PARAMETER['False_Easting',2000000.002616666],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-79.0],PARAMETER['Standard_Parallel_1',34.33333333333334],PARAMETER['Standard_Parallel_2',36.16666666666666],PARAMETER['Latitude_Of_Origin',33.75],UNIT['Foot_US',0.3048006096012192]];-121841900 -93659000 3048.00609601219;-100000 10000;-100000 10000;3.28083333333333E-03;0.001;0.001;IsHighPrecision", "")

# Process: Copy Features
arcpy.CopyFeatures_management(Adult_Arrest_Layer, Adult_Arrest, "", "0", "0", "0")

